name: Tests Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Format, tidy dependencies, and verify
        run: make tidy
      - name: Run tests
        run: make test
